#!/usr/bin/python
""" Generate html files for all election tickets

1. Read barcode images filename that be generated by step1_generate_barcode.py from /app/images/ folder
2. Read template file which is question.html
3, taking image filename as image URL, then paste it to question.html template
4. save each of them as *.html files.
"""

import os

BUILDING=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

for b in BUILDING:
  all_files = os.listdir('../app/images/barcode/building-%s/' % b)

  if not os.path.exists('./out/building-%s' % b):
    os.makedirs('./out/building-%s' % b)

  for file in all_files:
    f_template = open('question.html', 'r')
    file_content = f_template.read()

    new_html = file_content.replace('FIXME', 'http:/localhost:8080/images/barcode/%s' % file)
    write_as_html_1 = open( './out/building-%s/' % b + file.split('.')[0] + '.html', 'w'  )
    write_as_html_1.write(new_html)

    write_as_html_2 = open( './out/building-%s/' % b + file.split('.')[0] + '.html', 'r'  )
    do2_file_content = write_as_html_2.read()
    new_html = do2_file_content.replace('FIXNUMBER', file.split('.')[0])

    write_as_html_3 = open( './out/building-%s/' % b +file.split('.')[0] + '.html', 'w'  )
    write_as_html_3.write(new_html)

    write_as_html_3.close()
    write_as_html_2.close()
    write_as_html_1.close()
